Repository FollowMe-team/RunningMate-Backend, pull requests merged in 2024-12, with the labels that each got.

#29 [FIX] 타인 프로필 조회 및 발자국 조회 API 수정
  src/main/java/com/follow_me/running_mate/domain/member/controller/MemberController.java
  src/main/java/com/follow_me/running_mate/domain/member/dto/response/MemberResponse.java
  src/main/java/com/follow_me/running_mate/domain/member/mapper/MemberMapper.java
  src/main/java/com/follow_me/running_mate/domain/member/repository/MemberFollowRepository.java
  src/main/java/com/follow_me/running_mate/domain/member/service/MemberServiceImpl.java
Labels: :rotating_light: hotfix

#30 [FIX] 크루 생성 이슈 해결
  src/main/java/com/follow_me/running_mate/domain/crew/controller/CrewController.java
  src/main/java/com/follow_me/running_mate/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/follow_me/running_mate/domain/crew/entity/Crew.java
  src/main/java/com/follow_me/running_mate/domain/crew/entity/CrewSchedule.java
  src/main/java/com/follow_me/running_mate/domain/crew/mapper/CrewResponseMapper.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewService.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/follow_me/running_mate/domain/member/controller/AuthController.java
  src/main/java/com/follow_me/running_mate/domain/member/controller/MemberController.java
  src/main/java/com/follow_me/running_mate/domain/member/dto/response/MemberResponse.java
Labels: :bug: bug, :rotating_light: hotfix

#32 [FIX] 크루 삭제 시 완전 삭제
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewServiceImpl.java
Labels: :rotating_light: hotfix

#34 fix: 크루 reponse 반환값 수정
  src/main/java/com/follow_me/running_mate/domain/crew/mapper/CrewResponseMapper.java
Labels: :rotating_light: hotfix

#35 [FIX]swagger 예시 가독성 추가
  src/main/java/com/follow_me/running_mate/domain/crew/controller/CrewController.java
Labels: :rotating_light: hotfix

#37 [FIX] course 조회 respone 수정
  src/main/java/com/follow_me/running_mate/domain/course/dto/response/CourseResponse.java
  src/main/java/com/follow_me/running_mate/domain/course/mapper/CourseResponseMapper.java
  src/main/java/com/follow_me/running_mate/domain/course/service/CourseServiceImpl.java
Labels: ✨ feature

#36 [FIX] 회원 탈퇴시 크루 삭제
  src/main/java/com/follow_me/running_mate/domain/crew/controller/CrewController.java
  src/main/java/com/follow_me/running_mate/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/follow_me/running_mate/domain/crew/repository/CrewRepository.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewService.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/follow_me/running_mate/domain/member/service/MemberServiceImpl.java
Labels: :bug: bug, :rotating_light: hotfix

#38 [FEAT] 크루 신청 , 취소시 status 값 반환
  src/main/java/com/follow_me/running_mate/domain/crew/controller/CrewController.java
  src/main/java/com/follow_me/running_mate/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewService.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewServiceImpl.java
Labels: ✨ feature

#41 [FEAT] crew 멤버 리스트 조회 api
  src/main/java/com/follow_me/running_mate/domain/course/dto/request/CourseRequest.java
  src/main/java/com/follow_me/running_mate/domain/course/dto/response/CourseResponse.java
  src/main/java/com/follow_me/running_mate/domain/course/mapper/CourseEntityMapper.java
  src/main/java/com/follow_me/running_mate/domain/course/mapper/CourseResponseMapper.java
  src/main/java/com/follow_me/running_mate/domain/course/repository/CourseReviewRepository.java
  src/main/java/com/follow_me/running_mate/domain/course/service/CourseServiceImpl.java
  src/main/java/com/follow_me/running_mate/domain/course/service/review/CourseReviewService.java
  src/main/java/com/follow_me/running_mate/domain/course/service/review/CourseReviewServiceImpl.java
  src/main/java/com/follow_me/running_mate/domain/crew/controller/CrewController.java
  src/main/java/com/follow_me/running_mate/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/follow_me/running_mate/domain/crew/mapper/CrewResponseMapper.java
  src/main/java/com/follow_me/running_mate/domain/crew/repository/CrewMemberRepository.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewService.java
  src/main/java/com/follow_me/running_mate/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/follow_me/running_mate/global/common/util/FormatterUtil.java
Labels: ✨ feature
